name: mwm_workflow

on:
  push:
    branches: [ mwm_start ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Get dependencies
       run: apt-get dist-upgrade
     - name: auto configure
       run: autoconf
     - name: configure
       run: ./configure
     - name: make
       run: make
     - name: make check
       run: make check
     - name: make distcheck
       run: make distcheck
