
name: mwm_workflow


on:
  push:
    
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - name: Get netCDF
       run: sudo apt-get install libnetcdf-dev
     - name: auto configure
       run: autoreconf -i
     - name: configure
       run: ./configure
     - name: make -j distcheck
       run: make -j distcheck
