name: mwm_workflow

on:
  push:
    branches: [ mwmw-fixactions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#      - uses: actions/checkout@v2
#      - name: Get dependencies
#        run: sudo apt-get dist-upgrade
     - name: Get netCDF
       run: sudo apt-get install libnetcdf-dev
     - name: auto configure
       run: autoreconf -i
     - name: configure
       run: ./configure
     - name: make -j distcheck
       run: make -j distcheck
